name = "cdn-proxy"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Production
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "preludiolab-storage"
preview_bucket_name = "preludiolab-storage" # ローカル開発(--remote)で同じバケットを参照するために一時的に指定

# Preview (Optional)
# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "preludio-storage-preview"
# preview_bucket_name = "preludio-storage-preview"

[observability]
enabled = true
